### ISSUE TITLE
All-caps in CSS

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/herman-melville_moby-dick#3]
Generally we prefer not to have all-caps in almost all cases. Can we just remove the `b.alt` class entirely and use regular small-caps for `dfn`?

**Comment by robinwhittleton** [comment]
Sure, fixed in https://github.com/robinwhittleton/herman-melville_moby-dick/commit/db7fcb6837366e4ffbe30fdb69b012e6ba756913.
