### ISSUE TITLE
Affghanistan -> Afghanistan

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/herman-melville_moby-dick#4]
I think this would be a pretty straightforward and uncontroversial modernization. The name of the place is not changed, simply the spelling of the same name. (Unlike, say, Calcutta -> Kolkata)

**Comment by robinwhittleton** [comment]
Fixed in https://github.com/robinwhittleton/herman-melville_moby-dick/commit/57462ac23d7a312196c42b4c7fca4cc0c0cc19a2
