### ISSUE TITLE
Styling in drama-type passages?

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/herman-melville_moby-dick#6]
Would it make sense to use regular `table`s to style the drama-type sections, instead of having the character head a paragraph? This is the style we used for example in Nightmare Abbey.

**Comment by robinwhittleton** [comment]
I had a stab at this, and while I’m sure it’s doable it feels like it might be massaging the text a little far. In Nightmare Abbey there’s definitely one person speaking at a time, a stage direction refers to a single person, and it always comes at the start of a run of text. In Moby Dick it’s a fair bit more complex. For example, we have stage directions that effectively include personas: https://github.com/robinwhittleton/herman-melville_moby-dick/blob/af95e21530a47895d9f71a3fc7136ffa0f266ed9/src/epub/text/chapter-40.xhtml#L25-L29
Or with anonymous personas and the same styles from Nightmare Abbey we get this poor rendering:
![Massive left col](https://user-images.githubusercontent.com/7414/37992640-95dec886-320c-11e8-8080-afe72e5e164d.png)
Again, nothing that couldn’t be fixed, but, well…
Anyway, up to you. Like I said, nothing that can’t be fixed, it’s just going to take a bit of finessing to get right.

**Comment by acabal** [comment]
OK, let's leave it as-is then.
